<?= $this->Html->css('//fonts.googleapis.com/css?family=Open+Sans:400,600,700&amp;subset=vietnamese') ?>
<?= $this->Html->css('//fonts.googleapis.com/css?family=Noto+Serif:400,600,700&amp;subset=vietnamese') ?>
<?= $this->Html->css('/frontend/css/poppins') ?>
<?= $this->Html->css('/frontend/libs/bootstrap/css/bootstrap.min'); ?>
<?= $this->Html->css('/frontend/libs/fontawesome/css/all.min'); ?>
<?= $this->Html->css('/frontend/css/hotel-font'); ?>
<?= $this->Html->css('/frontend/mustgo-font/styles'); ?>
<?= $this->Html->css('/frontend/libs/bxslider/dist/jquery.bxslider.min'); ?>
<?= $this->Html->css('/frontend/libs/lightGallery/dist/css/lightgallery.min'); ?>
<?= $this->Html->css('/frontend/libs/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min'); ?>
<?= $this->Html->css('/backend/vendors/bootstrap-daterangepicker/daterangepicker'); ?>
<?= $this->Html->css('/frontend/libs/icheck/skins/all'); ?>
<?= $this->Html->css('/frontend/libs/boostrapselect/css/bootstrap-multiselect'); ?>
<?= $this->Html->css('/frontend/libs/bootstrap-pretty-tables.min'); ?>
<?= $this->Html->css('/frontend/libs/bootstrap-slider/slider.css'); ?>
<?= $this->Html->css('/frontend/css/normalize'); ?>
<?= $this->Html->css('/frontend/css/common'); ?>
<?= $this->Html->css('/frontend/css/style'); ?>
<?= $this->Html->css('/frontend/css/responsive'); ?>
